[tool.black]
line-length = 88
target-version = ['py311']  # Adjust this to your Python version
include = '\.pyi?$'       # Include Python files
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | build\.d
)/
'''
